#!/usr/bin/env node
/**
 * chrome_backfill.js
 * Uses Puppeteer (real Chrome) to scrape blogger + rating for recipes
 * that blocked the Python requests scraper.
 *
 * Usage:
 *   node chrome_backfill.js
 *
 * Reads:  /tmp/missing_recipes.json  (generated by Python)
 * Writes: /tmp/chrome_backfill_results.json
 */

const puppeteer = require('puppeteer');
const fs = require('fs');

const MISSING = JSON.parse(fs.readFileSync('/tmp/missing_recipes.json', 'utf8'));
const RESULTS_FILE = '/tmp/chrome_backfill_results.json';
const SLEEP_MS = 1200;

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

async function scrape(page, url) {
  try {
    await page.goto(url, { waitUntil: 'domcontentloaded', timeout: 20000 });
  } catch(e) {
    return { error: e.message };
  }

  return page.evaluate(() => {
    const result = { blogger: '', rating: '' };

    // og:site_name → blogger
    const ogSite = document.querySelector('meta[property="og:site_name"]');
    if (ogSite) result.blogger = ogSite.content.trim();
    if (!result.blogger) {
      const domain = location.hostname.replace('www.', '');
      result.blogger = domain.split('.')[0].replace(/-/g,' ')
        .replace(/\b\w/g, c => c.toUpperCase());
    }

    // JSON-LD → rating
    const scripts = document.querySelectorAll('script[type="application/ld+json"]');
    for (const s of scripts) {
      try {
        const data = JSON.parse(s.textContent);
        const items = data['@graph'] ? data['@graph'] : [data];
        for (const item of items) {
          if (item['@type'] === 'Recipe' && item.aggregateRating) {
            const rv = item.aggregateRating.ratingValue;
            const rc = item.aggregateRating.ratingCount || item.aggregateRating.reviewCount || '';
            if (rv) {
              result.rating = rc ? `${parseFloat(rv).toFixed(1)} (${rc} ratings)` : `${parseFloat(rv).toFixed(1)}`;
            }
            break;
          }
        }
      } catch(_) {}
    }

    return result;
  });
}

(async () => {
  const browser = await puppeteer.launch({
    headless: true,
    args: ['--no-sandbox', '--disable-setuid-sandbox',
           '--user-agent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36']
  });
  const page = await browser.newPage();
  await page.setExtraHTTPHeaders({ 'Accept-Language': 'en-US,en;q=0.9' });

  const results = {};
  let patched = 0;

  for (let i = 0; i < MISSING.length; i++) {
    const rec = MISSING[i];
    process.stdout.write(`[${i+1}/${MISSING.length}] ${rec.name} ... `);

    const scraped = await scrape(page, rec.url);

    const patch = {};
    if (rec.missing.includes('blogger') && scraped.blogger) patch.blogger = scraped.blogger;
    if (rec.missing.includes('rating')  && scraped.rating)  patch.rating  = scraped.rating;

    if (Object.keys(patch).length > 0) {
      results[rec.id] = patch;
      patched++;
      console.log(`✓ ${JSON.stringify(patch)}`);
    } else {
      console.log(`— nothing (${scraped.error || 'no data found'})`);
    }

    await sleep(SLEEP_MS);
  }

  await browser.close();

  fs.writeFileSync(RESULTS_FILE, JSON.stringify(results, null, 2));
  console.log(`\nDone. ${patched}/${MISSING.length} patched. Results saved to ${RESULTS_FILE}`);
})();
