/**
 * batch_enrich.js
 * ───────────────
 * Enriches ALL 948 YES recipes in Firestore.
 * Only fills in missing fields — skips anything already present.
 *
 * Fields filled per recipe:
 *   1. ingredients  — scraped from recipe URL
 *   2. dietTags     — all 8 protocols (AIP, LF, Keto, GF, DF, V, VG, LH)
 *   3. chefsNotes   — generated by Claude (only when mods are needed)
 *   4. menuDescription — generated by Claude (e.g. "pan-seared salmon; lemon butter; herb oil")
 *
 * Usage:
 *   node batch_enrich.js
 *   node batch_enrich.js --concurrency 5   (default: 3)
 *   node batch_enrich.js --reset            (clear progress, start fresh)
 *
 * Progress is saved to batch_enrich_progress.json — safe to Ctrl+C and resume.
 */

const admin    = require('firebase-admin');
const axios    = require('./functions/node_modules/axios').default || require('./functions/node_modules/axios');
const cheerio  = require('./functions/node_modules/cheerio');
const Anthropic = require('./functions/node_modules/@anthropic-ai/sdk');
const dietRules = require('./functions/diet-rules.json');
const fs       = require('fs');
const path     = require('path');

// ── Config ────────────────────────────────────────────────────────────────────

const PROGRESS_FILE = path.join(__dirname, 'batch_enrich_progress.json');
const SERVICE_ACCOUNT = require('./service-account.json');

// Read ANTHROPIC_API_KEY from functions/.env
const envPath = path.join(__dirname, 'functions', '.env');
const envContent = fs.readFileSync(envPath, 'utf8');
const apiKeyMatch = envContent.match(/ANTHROPIC_API_KEY=(.+)/);
if (!apiKeyMatch) { console.error('ANTHROPIC_API_KEY not found in functions/.env'); process.exit(1); }
process.env.ANTHROPIC_API_KEY = apiKeyMatch[1].trim();

// CLI args
const args = process.argv.slice(2);
const CONCURRENCY = parseInt(args.find(a => a.startsWith('--concurrency='))?.split('=')[1] || '3', 10) ||
  (args.includes('--concurrency') ? parseInt(args[args.indexOf('--concurrency') + 1], 10) : 3);
const RESET = args.includes('--reset');

// ── Firebase init ─────────────────────────────────────────────────────────────

if (!admin.apps.length) {
  admin.initializeApp({ credential: admin.credential.cert(SERVICE_ACCOUNT) });
}
const db = admin.firestore();
const anthropic = new Anthropic.default({ apiKey: process.env.ANTHROPIC_API_KEY });

// ── Progress tracking ─────────────────────────────────────────────────────────

function loadProgress() {
  if (RESET && fs.existsSync(PROGRESS_FILE)) fs.unlinkSync(PROGRESS_FILE);
  if (!fs.existsSync(PROGRESS_FILE)) return { done: [], errors: [] };
  try { return JSON.parse(fs.readFileSync(PROGRESS_FILE, 'utf8')); }
  catch(_) { return { done: [], errors: [] }; }
}

function saveProgress(progress) {
  fs.writeFileSync(PROGRESS_FILE, JSON.stringify(progress, null, 2));
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }

function capitalise(str) { return str.charAt(0).toUpperCase() + str.slice(1); }

function pad(str, len) {
  const s = String(str);
  return s.length >= len ? s : s + ' '.repeat(len - s.length);
}

// ── Step 1: Scrape Ingredients ────────────────────────────────────────────────

async function scrapeIngredients(url) {
  try {
    const res = await axios.get(url, {
      timeout: 15000,
      headers: {
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
        'Accept': 'text/html,application/xhtml+xml,*/*;q=0.8',
      },
    });

    const $ = cheerio.load(res.data);

    // JSON-LD first (most reliable)
    const jsonLdScripts = $('script[type="application/ld+json"]');
    for (let i = 0; i < jsonLdScripts.length; i++) {
      try {
        const parsed = JSON.parse($(jsonLdScripts[i]).html());
        const items = parsed['@graph'] ? parsed['@graph'] : (Array.isArray(parsed) ? parsed : [parsed]);
        for (const item of items) {
          if (item['@type'] === 'Recipe' && Array.isArray(item.recipeIngredient) && item.recipeIngredient.length) {
            return item.recipeIngredient.filter(Boolean);
          }
        }
      } catch (_) {}
    }

    // HTML fallbacks
    const selectors = [
      '.wprm-recipe-ingredient',
      '.tasty-recipes-ingredients-body li',
      '.recipe-ingredients li',
      '[class*="ingredient"] li',
      '.ingredients li',
      '[itemprop="recipeIngredient"]',
    ];
    for (const sel of selectors) {
      const items = [];
      $(sel).each((_, el) => { const t = $(el).text().trim(); if (t) items.push(t); });
      if (items.length > 0) return items;
    }

    return [];
  } catch (err) {
    return [];
  }
}

// ── Step 2: Diet Compliance Analysis ─────────────────────────────────────────

function analyzeDietCompliance(ingredients, name, description, url, blogger) {
  const ingredientText = ingredients.join(' ').toLowerCase();
  const contextText    = `${name} ${description} ${blogger}`.toLowerCase();
  const allText        = `${ingredientText} ${contextText}`;
  const result         = {};

  for (const [tag, rules] of Object.entries(dietRules)) {
    const hasQualifier       = rules.native_qualifiers.some(q => allText.includes(q.toLowerCase()));
    const disqualifiers      = rules.native_disqualifiers.filter(d => ingredientText.includes(d.toLowerCase()));
    const isNativelyDisqualified = disqualifiers.length > 0;

    let native = false, mod = false, notes = '';

    if (hasQualifier && !isNativelyDisqualified) {
      native = true;
    } else if (!isNativelyDisqualified && ingredients.length > 0) {
      native = true;
    }

    if (!native) {
      if (tag === 'LF' && rules.skip_if_star) {
        const nameLC = name.toLowerCase();
        if (rules.skip_if_star.some(s => nameLC.includes(s))) {
          result[tag] = { native: false, mod: false, notes: '' };
          continue;
        }
      }

      const modCandidates = (rules.mod_candidates || []).filter(c => ingredientText.includes(c.toLowerCase()));
      if (modCandidates.length > 0) {
        const swapNotes = modCandidates
          .map(c => { const swap = rules.swaps?.[c]; return swap ? `${capitalise(c)}: ${swap}.` : null; })
          .filter(Boolean);
        if (swapNotes.length > 0) { mod = true; notes = swapNotes.join(' '); }
      }
    }

    if (native || mod) {
      result[tag] = { native, mod, notes };
    }

    if (tag === 'AIP' && (native || mod) && rules.cascade_tags) {
      for (const ct of rules.cascade_tags) {
        if (!result[ct]) result[ct] = { native: true, mod: false, notes: '' };
      }
    }
  }

  return result;
}

// ── Step 3: Generate Chef's Notes ─────────────────────────────────────────────

async function generateChefsNotes(name, ingredients, dietTags, existing) {
  if (existing && existing.trim()) return existing;

  const modsNeeded = Object.entries(dietTags)
    .filter(([, v]) => v.mod && v.notes)
    .map(([k, v]) => `${k}: ${v.notes}`);

  if (modsNeeded.length === 0) return '';

  try {
    const msg = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 200,
      messages: [{
        role: 'user',
        content: `You are writing chef's notes for the CKC (Curated Kitchen Collective) recipe app. Write concise, first-person "We" modification notes for the recipe "${name}".

Ingredients: ${ingredients.slice(0, 30).join(', ')}

The following diet modifications are needed:
${modsNeeded.join('\n')}

Write 1-3 sentences in first person using "We" (e.g. "We swap the flour tortillas for corn tortillas to keep this gluten-free..."). Be specific, practical, and helpful. Do not mention protocols by abbreviation — write naturally. No bullet points, no headers. Plain paragraph.`,
      }],
    });
    return msg.content[0].text.trim();
  } catch (_) { return ''; }
}

// ── Step 4: Generate Menu Description ────────────────────────────────────────

async function generateMenuDescription(name, ingredients, existing) {
  if (existing && existing.trim() && existing.includes(';')) return existing;

  try {
    const msg = await anthropic.messages.create({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 80,
      messages: [{
        role: 'user',
        content: `Write a short, elegant menu-style description for the recipe "${name}".

Ingredients: ${ingredients.slice(0, 20).join(', ')}

Format: 3-5 lowercase components separated by semicolons (e.g. "slow-braised lamb; pomegranate reduction; herb gremolata; roasted garlic"). No sentence, no capital letters except proper nouns, no period at the end. Evoke the dish poetically but accurately.`,
      }],
    });
    return msg.content[0].text.trim();
  } catch (_) { return ''; }
}

// ── Process one recipe ────────────────────────────────────────────────────────

async function enrichRecipe(doc, index, total) {
  const data = doc.data();
  const id   = doc.id;
  const name = (data.name || 'Unknown').slice(0, 45);
  const label = `[${index}/${total}] ${pad(name, 45)}`;

  // Determine what needs to be done
  const needsIngredients     = !data.ingredients?.length && !!data.url;
  const needsDietTags        = !data.dietTags || Object.keys(data.dietTags).length === 0;
  const needsMenuDescription = !data.menuDescription || !data.menuDescription.includes(';');
  // chefsNotes only generated when mods exist — handled inside generateChefsNotes

  // If nothing to do, skip
  if (!needsIngredients && !needsDietTags && !needsMenuDescription && data.chefsNotes !== undefined) {
    console.log(`${label} ✓ already complete`);
    return { status: 'skipped' };
  }

  try {
    // Step 1: Ingredients
    let ingredients = data.ingredients || [];
    if (needsIngredients) {
      ingredients = await scrapeIngredients(data.url);
    }

    // Step 2: Diet tags
    let dietTags = data.dietTags || {};
    if (needsDietTags || (needsIngredients && ingredients.length > 0)) {
      dietTags = analyzeDietCompliance(
        ingredients, data.name || '', data.description || '', data.url || '', data.blogger || ''
      );
    }

    // Small delay before Claude calls to respect rate limits
    await sleep(300);

    // Step 3: Chef's notes
    const chefsNotes = await generateChefsNotes(data.name, ingredients, dietTags, data.chefsNotes || '');

    // Step 4: Menu description
    await sleep(200);
    const menuDescription = await generateMenuDescription(data.name, ingredients, data.menuDescription || '');

    // Build update object — only set fields we actually worked on
    const update = {
      enrichedAt: admin.firestore.FieldValue.serverTimestamp(),
      enrichmentError: admin.firestore.FieldValue.delete(),
    };
    if (ingredients.length > 0 || needsIngredients) update.ingredients = ingredients;
    if (Object.keys(dietTags).length > 0) update.dietTags = dietTags;
    if (chefsNotes) update.chefsNotes = chefsNotes;
    if (menuDescription) update.menuDescription = menuDescription;

    await db.collection('recipes').doc(id).update(update);

    const flags = [
      ingredients.length ? `${ingredients.length} ingr` : '',
      Object.keys(dietTags).length ? `${Object.keys(dietTags).length} tags` : '',
      chefsNotes ? 'notes' : '',
      menuDescription ? 'menu✓' : '',
    ].filter(Boolean).join(' | ');

    console.log(`${label} ✓ ${flags}`);
    return { status: 'done' };

  } catch (err) {
    console.log(`${label} ✗ ${err.message.slice(0, 60)}`);
    return { status: 'error', error: err.message };
  }
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  console.log('CKC Batch Enrichment');
  console.log(`Concurrency: ${CONCURRENCY}`);
  console.log('Fetching YES recipes from Firestore…\n');

  const snap = await db.collection('recipes').where('status', '==', 'yes').get();
  const allDocs = snap.docs;
  const total   = allDocs.length;

  console.log(`Total YES recipes: ${total}`);

  // Load progress
  const progress = loadProgress();
  const doneSet  = new Set(progress.done);

  // Filter to unprocessed
  const todo = allDocs.filter(d => !doneSet.has(d.id));
  console.log(`Already done: ${doneSet.size} | Remaining: ${todo.length}\n`);

  let processed = 0, skipped = 0, errors = 0;
  const startIndex = doneSet.size;

  // Process in batches of CONCURRENCY
  for (let i = 0; i < todo.length; i += CONCURRENCY) {
    const batch = todo.slice(i, i + CONCURRENCY);

    const results = await Promise.all(
      batch.map((doc, bi) => enrichRecipe(doc, startIndex + i + bi + 1, total))
    );

    results.forEach((r, ri) => {
      const docId = batch[ri].id;
      if (r.status === 'done' || r.status === 'skipped') {
        progress.done.push(docId);
        if (r.status === 'done') processed++;
        else skipped++;
      } else {
        progress.errors.push({ id: docId, error: r.error });
        errors++;
        progress.done.push(docId); // mark done so we don't retry infinitely
      }
    });

    // Save progress every batch
    saveProgress(progress);

    // Brief pause between batches to be polite to APIs
    if (i + CONCURRENCY < todo.length) await sleep(500);
  }

  console.log('\n── Summary ──');
  console.log(`  Enriched:  ${processed}`);
  console.log(`  Skipped:   ${skipped}`);
  console.log(`  Errors:    ${errors}`);
  console.log(`  Total:     ${total}`);

  process.exit(0);
}

main().catch(err => { console.error(err); process.exit(1); });
